---
driver:
  name: vagrant
  customize:
    cpus: 2
    memory: 1024

provisioner:
  name: policyfile_zero
  require_chef_omnibus: 12.6.0

platforms:
  # TODO: (jtimberman) Add ubuntu later, MVP is CentOS 7
  # - name: ubuntu-14.04
  - name: centos-7.2

suites:
  - name: default
    run_list:
      - recipe[chef-reference::default]
    attributes:
